project:
  type: website
  output-dir: docs
  
website: 
  title: "Project 1"
  navbar:
    left: 
      - href: Function Code.qmd
        text: "Functions"
      - href: Narrative & Examples.qmd
        text: "Narrative & Examples"
        
format: 
  html: 
    theme: cosmo